---
title: "Simon Müller's CV"
author: Simon Müller
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1urM7Art9-zrZcMjFGS13GDdrg1J1KvnrHFK8Tgtd0bo/edit?usp=sharing",  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
datadrivencv::build_network_logo(CV$entries_data)
```


```{r}
if(params$pdf_mode){
  cat("View this CV online with links at _https://sites.google.com/view/simons-portfolio-now/_")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/mosoho/cv/simon_mueller_cv.pdf)")
}
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV |> print_contact_info()
```



Language Skills {#skills}
--------------------------------------------------------------------------------

```{r}
CV |> print_skill_bars()
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R package [**pagedown**](https://github.com/rstudio/pagedown). 

The source code is available [on github.com/mosoho/cv](https://github.com/mosoho/cv).

Last updated on `r Sys.Date()`.



Main
================================================================================

Simon Müller {#title}
--------------------------------------------------------------------------------

```{r}
# Note the assignment back to CV. This is so the link stripping works properly in PDF mode
CV <- print_text_block(CV, "intro") 
```



Arbeitserfahrung {data-icon=suitcase}
--------------------------------------------------------------------------------

::: aside
```{r}
CV <- print_text_block(CV, 'arbeitserfahrung_aside')
```
:::

```{r}
CV <- print_section(CV, 'arbeitserfahrung')
```



Ausbildung {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV <- print_section(CV, 'ausbildung')
```



Research Experience {data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
CV <- print_section(CV, 'research_positions')
```



<!-- These breaks just force a new page so section doesnt get cut off -->
<br>
<br>
<br>

Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

::: aside
```{r}
CV <- print_text_block(CV, 'teaching_experience_aside')
```
:::

```{r}
CV <- print_section(CV, 'teaching_positions')
```



Selected Data Science Writing {data-icon=chart-line}
--------------------------------------------------------------------------------

::: aside
```{r}
CV <- print_text_block(CV, 'data_science_writing_aside')
```
:::

```{r}
CV <- print_section(CV, 'data_science_writings')
```



Selected Press (About)  {data-icon=newspaper}
--------------------------------------------------------------------------------

```{r}
CV <- print_section(CV, 'about_me_press')
```


<br>
<br>


Selected Press (By)  {data-icon=newspaper}
--------------------------------------------------------------------------------

```{r}
CV <- print_section(CV, 'by_me_press')
```



Selected Publications, Posters, and Talks {data-icon=book}
--------------------------------------------------------------------------------

```{r}
CV <- print_section(CV, 'academic_articles')
```



```{r}
print_links(CV)
```

